### ISSUE TITLE
tina-modal 引用失败

### ISSUE THREAD

**Issue by callmesoul** [tinajs/tina-modal#1]
tina:0.22
app.mina
```
<script>
  import Tina from '@tinajs/tina'
  import router from '@tinajs/tina-router'
  import { modal } from '@tinajs/tina-modal'

  Tina.use(router).use(modal);
App({
  onLaunch() {
  },
})
</script>
```

page.mina:
```
<script>
  import {Page} from '@tinajs/tina'
Page.define({
  onLoad(){
    this.$confirm({ content: 'say hi?' })
      .then(() => this.$alert({ content: 'hi' }))
  }
})
</script>
```

开发工具报错：
```
VM23752:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'install' of undefined 
 TypeError: Cannot read property 'install' of undefined
    at Function.use (http://127.0.0.1:60306/appservice/common.js:1059:24)
    at Module.14 (http://127.0.0.1:60306/appservice/app.js:24:117)
    at __webpack_require__ (http://127.0.0.1:60306/appservice/runtime.js:79:30)
    at Object.0 (http://127.0.0.1:60306/appservice/app.js:6:2)
    at __webpack_require__ (http://127.0.0.1:60306/appservice/runtime.js:79:30)
    at checkDeferredModules (http://127.0.0.1:60306/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:60306/appservice/runtime.js:33:19)
    at http://127.0.0.1:60306/appservice/app.js:1:520
    at require (http://127.0.0.1:60306/appservice/__dev__/WAService.js:1:716549)
    at <anonymous>:1:1
console.error @ VM23752:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1542762003086:1164
window.onerror @ VM23752:1
scriptLoaded @ appservice?t=1542762003086:1230

```

**Comment by callmesoul** [comment]
import { modal } from '@tinajs/tina-modal'
改成
import modal  from '@tinajs/tina-modal'
既可

tina 文档写的是 import { modal } from '@tinajs/tina-modal'

**Comment by imyelo** [comment]
谢谢反馈 😊
